server:
  shutdown: graceful

application:
  version: ${MES_RELEASE_VERSION}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  flyway:
    enabled: true
    out-of-order: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${MES_DB_HOST}:${MES_DB_PORT:3306}/${MES_DB_NAME}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: ${MES_DB_USERNAME}
    password: ${MES_DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
